# docker-compose up -d --build

services:
  app:
    container_name: bff_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5102"
    depends_on:
      - "session_cache"
    restart: always
    environment:
      - REDIS_CONNECTION_STRING=redis://session_cache:6379
      - AUTHENTICATION_SERVICE_URL=http://localhost:5001
      - NOTE_TREE_SERVICE_URL=http://localhost:5003

  session_cache:
    image: redis/redis-stack-server:latest
    container_name: session_cache
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - session_cache_volume:/var/lib/redis

volumes:
  session_cache_volume:
