# docker-compose up -d --build

services:
  bff_app:
    container_name: bff_app
    image: farukerat/bff_app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5002:5102"
    depends_on:
      - "session_cache"
    restart: always
    environment:
      - REDIS_CONNECTION_STRING=redis://session_cache:6379
      - AUTHENTICATION_SERVICE_URL=http://auth_app:5101
      - NOTE_TREE_SERVICE_URL=http://note_trees_app:5103
    networks:
      - message_broker

  session_cache:
    image: redis/redis-stack-server:latest
    container_name: session_cache
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - session_cache_volume:/var/lib/redis
    networks:
      - message_broker

networks:
  message_broker:
    external: true
    name: message_broker
    driver: bridge

volumes:
  session_cache_volume:
