# docker-compose up -d --build

version: '3.3'

networks:
  dev:
    driver: bridge

services:
  app:
    image: farukerat/backend_for_frontend-image:latest
    container_name: app
    depends_on:
      - "session_cache"
    ports:
      - "5002:5102"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_CONNECTION_STRING=session_cache:6379,abortConnect=False
    networks:
      - dev

  session_cache:
    image: redis:latest
    container_name: session_cache
    ports:
      - "6379:6379"
    restart: always
    networks:
      - dev
    volumes:
      - session_cache_volume:/var/lib/redis

volumes:
  session_cache_volume:
