# docker-compose up --build -d

services:
  bff_app:
    container_name: bff_app
    image: farukerat/bff_app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${BFF_APP_EXPOSED_PORT}:5102
    depends_on:
      - session_cache
    restart: always
    environment:
      - REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING}
      - AUTHENTICATION_SERVICE_URL=${AUTHENTICATION_SERVICE_URL}
      - NOTE_TREE_SERVICE_URL=${NOTE_TREE_SERVICE_URL}
    networks:
      - message_broker
    # command for required plugin:
    # docker plugin install grafana/loki-docker-driver:2.9.2 --alias loki --grant-all-permissions

    # documentation:
    # https://grafana.com/docs/loki/latest/send-data/docker-driver/configuration/
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

  session_cache:
    image: redis/redis-stack-server:latest
    container_name: session_cache
    ports:
      - ${REDIS_EXPOSED_PORT}:6379
    restart: always
    volumes:
      - session_cache_volume:/var/lib/redis
    networks:
      - message_broker

networks:
  message_broker:
    external: true
    name: message_broker
    driver: bridge

volumes:
  session_cache_volume:
