# docker-compose up -d --build

version: '3.3'

networks:
  dev:
    driver: bridge

services:
  authentication-server:
    image: farukerat/backend_for_frontend-image:latest
    container_name: bff-app
    depends_on:
      - "app_cache"
    ports:
      - "5002:5102"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_CONNECTION_STRING=app_cache:6379,abortConnect=False
    networks:
      - dev

  app_cache:
    image: redis:latest
    container_name: cache
    ports:
      - "6379:6379"
    restart: always
    networks:
      - dev

volumes:
  app_data:
