# docker-compose up -d --build

version: '3.3'

networks:
  dev:
    driver: bridge

services:
  app:
    image: farukerat/NoteTrees-image:latest
    container_name: app
    depends_on:
      - "note_db"
    ports:
      - "5003:5103"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://note_db:27017
      - AUTHENTICATION_URL=http://localhost:5001
    networks:
      - dev

  note_db:
    image: mongo:latest
    container_name: note_db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - note_db_volume:/data/db
    networks:
      - dev

volumes:
  note_db_volume:
