# docker-compose up -d --build

services:
  note_trees_app:
    image: farukerat/note_trees-image:latest
    container_name: note_trees_app
    depends_on:
      - "note_db"
    ports:
      - "5003:5103"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGODB_CONNECTION_STRING=mongodb://note_db:27017
      - AUTHENTICATION_URL=http://auth_app:5101
      - RABBITMQ_HOST=localhost
      - RABBITMQ_USERNAME=superuser
      - RABBITMQ_PASSWORD=superuser
    networks:
      - message_broker

  note_db:
    image: mongo:latest
    container_name: note_db
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - note_db_volume:/data/db
    networks:
      - message_broker

networks:
  message_broker:
    external: true
    name: message_broker
    driver: bridge

volumes:
  note_db_volume:
