# docker-compose up -d --build

services:
  note_trees_app:
    container_name: note_trees_app
    image: farukerat/note_trees_app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${NOTE_TREES_APP_EXPOSED_PORT}:5103
    depends_on:
      - note_db
    restart: always
    environment:
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING}
      - AUTHENTICATION_URL=${AUTHENTICATION_URL}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    networks:
      - message_broker
    # command for required plugin:
    # docker plugin install grafana/loki-docker-driver:2.9.2 --alias loki --grant-all-permissions

    # documentation:
    # https://grafana.com/docs/loki/latest/send-data/docker-driver/configuration/
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

  note_db:
    image: mongo:latest
    container_name: note_db
    ports:
      - ${MONGO_DB_EXPOSED_PORT}:27017
    restart: always
    volumes:
      - note_db_volume:/data/db
    networks:
      - message_broker

networks:
  message_broker:
    external: true
    name: message_broker
    driver: bridge

volumes:
  note_db_volume:
