# docker-compose up -d --build

services:
  auth_app:
    container_name: auth_app
    image: farukerat/auth_app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5101"
    depends_on:
      - "user_db"
    restart: always
    environment:
      - POSTGRES_CONNECTION_STRING=Host=user_db;Database=NoteTrees;Username=postgres;Password=root;Pooling=true;
      - RABBITMQ_HOST=message_broker
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - message_broker

  user_db:
    image: postgres:latest
    container_name: user_db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - user_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=users
    networks:
      - message_broker

networks:
  message_broker:
    external: true
    name: message_broker
    driver: bridge

volumes:
  user_db_volume:
