# docker-compose up --build -d

services:
  auth_app:
    container_name: auth_app
    image: farukerat/auth_app:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${AUTH_APP_EXPOSED_PORT}:5101
    depends_on:
      - user_db
    restart: always
    environment:
      - POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    networks:
      - message_broker
    # command for required plugin:
    # docker plugin install grafana/loki-docker-driver:2.9.2 --alias loki --grant-all-permissions

    # documentation:
    # https://grafana.com/docs/loki/latest/send-data/docker-driver/configuration/
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push

  user_db:
    image: postgres:latest
    container_name: user_db
    ports:
      - ${POSTGRE_EXPOSED_PORT}:5432
    restart: always
    volumes:
      - user_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - message_broker

networks:
  message_broker:
    external: true
    name: message_broker
    driver: bridge

volumes:
  user_db_volume:
