# docker-compose up -d --build

version: '3.3'

networks:
  dev:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: farukerat/authentication-image:latest
    container_name: app
    depends_on:
      - "user_db"
    ports:
      - "5001:5101"
    restart: always
    environment:
      - POSTGRES_CONNECTION_STRING=Host=user_db;Database=NoteTrees;Username=postgres;Password=root;Pooling=true;
      - RABBITMQ_HOST=message_broker
      - RABBITMQ_USERNAME=superuser
      - RABBITMQ_PASSWORD=superuser
    networks:
      - dev

  user_db:
    image: postgres:latest
    container_name: user_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

  message_broker:
    image: rabbitmq:latest
    container_name: message_broker
    environment:
      - RABBITMQ_DEFAULT_USER=superuser
      - RABBITMQ_DEFAULT_PASS=superuser
    ports:
      - "5673:5672"
    restart: always
    volumes:
      - message_broker:/var/lib/message_broker
    networks:
      - dev

volumes:
  app_data:
  message_broker:
