# docker-compose up -d --build

version: '3.3'

networks:
  dev:
    driver: bridge

services:
  authentication-server:
    image: farukerat/authentication-image:latest
    container_name: auth-app
    depends_on:
      - "user_db"
    ports:
      - "5001:5101"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_CONNECTION_STRING=Host=user_db;Database=NoteTrees;Username=postgres;Password=root;Pooling=true;
    networks:
      - dev

  user_db:
    image: postgres:latest
    container_name: user_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=users
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data:
