# docker-compose up -d --build

services:
  app:
    container_name: auth_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5101"
    depends_on:
      - "user_db"
    restart: always
    environment:
      - POSTGRES_CONNECTION_STRING=Host=user_db;Database=NoteTrees;Username=postgres;Password=root;Pooling=true;
      - RABBITMQ_HOST=localhost
      - RABBITMQ_USERNAME=superuser
      - RABBITMQ_PASSWORD=superuser

  user_db:
    image: postgres:latest
    container_name: user_db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - user_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=users

volumes:
  user_db_volume:
